# Generated by Django 5.0.6 on 2024-06-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='miners',
            field=models.BooleanField(default=False),
        ),
    ]
